In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [5]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.shape(arr3)

(3, 3)

In [2]:
import pandas as pd

In [9]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [10]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [11]:
np.empty(5)

array([8.26645800e-312, 5.11798223e-307, 8.26645801e-312, 8.26645801e-312,
       9.34609790e-307])

In [12]:
np.zeros((10, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.randint(0, 10, (3, 3))

array([[7, 5, 2],
       [5, 8, 0],
       [6, 2, 1]])

In [20]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [30]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_array[5]

5

In [32]:
my_array[-1]

9

In [33]:
my_array[3:6]

array([3, 4, 5])

In [34]:
my_array[1:8:3]

array([1, 4, 7])

In [35]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2]

12

In [36]:
my_array[1,2]

12

In [37]:
my_array[1]

array([10, 11, 12, 13])

In [42]:
my_array[:,0:2]

array([[ 1,  2],
       [10, 11],
       [45, 46]])

In [40]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

In [56]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [46]:
big_secret[:,-1].sum()

3154.332495807108

In [50]:
big_secret[:,:5].diagonal().sum()

121.37188663699624

In [51]:
big_secret[:,-5:].diagonal().prod()

341505315559.2347

In [53]:
my_array = np.random.randint(1, 100, (4, 6))
my_array

array([[41, 21, 34, 38, 94, 61],
       [ 1, 22, 25, 86, 62, 69],
       [97, 64,  9, 56, 21, 32],
       [77, 58, 24, 21, 53, 91]])

In [54]:
my_slice = my_array[1:3, 2:4]

In [55]:
my_slice[:] = 0
my_array

array([[41, 21, 34, 38, 94, 61],
       [ 1, 22,  0,  0, 62, 69],
       [97, 64,  0,  0, 21, 32],
       [77, 58, 24, 21, 53, 91]])

In [57]:
for x in range(big_secret.shape[0]):
    for y in range(big_secret.shape[1]):
        if x % 2 == 0 and y % 2 == 0:
            big_secret[x, y] = -1
        elif x % 2 != 0 and y % 2 != 0:
            big_secret[x, y] = 1

In [59]:
big_secret[:,:5].diagonal().sum()

-1.0

In [60]:
big_secret[:,-5:].diagonal().prod()

-1.0

In [61]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print(f'Сумма: {result1}\nРазность: {result2}\nПроизведение: {result3}\nЧастное: {result4}\nУмножение на число: {result5}')

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [4]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [5]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [7]:
my_array = np.random.randint(0, 10, 20)

In [8]:
my_array

array([8, 6, 4, 6, 5, 6, 3, 6, 8, 5, 9, 5, 1, 0, 6, 1, 8, 6, 1, 1])

In [9]:
my_array.reshape((4,5))

array([[8, 6, 4, 6, 5],
       [6, 3, 6, 8, 5],
       [9, 5, 1, 0, 6],
       [1, 8, 6, 1, 1]])

In [10]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])

In [11]:
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [12]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [13]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[0, 7, 1, 0],
       [7, 4, 0, 1],
       [7, 3, 8, 0]])

In [14]:
my_array<5

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [False,  True, False,  True]])

In [15]:
my_array[my_array<5]

array([0, 1, 0, 4, 0, 1, 3, 0])

In [16]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[0, 1],
       [7, 0],
       [7, 8]])

In [18]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[9, 7, 6, 4, 8, 9],
       [5, 8, 1, 7, 2, 4],
       [1, 9, 3, 5, 4, 6],
       [4, 8, 4, 8, 4, 8]])

In [19]:
np.sort(my_array, axis=1)

array([[4, 6, 7, 8, 9, 9],
       [1, 2, 4, 5, 7, 8],
       [1, 3, 4, 5, 6, 9],
       [4, 4, 4, 8, 8, 8]])

In [20]:
np.sort(my_array, axis=0)

array([[1, 7, 1, 4, 2, 4],
       [4, 8, 3, 5, 4, 6],
       [5, 8, 4, 7, 4, 8],
       [9, 9, 6, 8, 8, 9]])

In [21]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [22]:
great_secret.shape

(100, 3)

In [23]:
np.cos(great_secret[0]).sum()

0.16006721889793019

In [24]:
great_secret[great_secret > 50].sum()

5470.0

In [25]:
flat_great_secret = great_secret.flatten()
flat_great_secret[150]

7.0710678118654755

In [28]:
sort_gs = np.sort(great_secret, axis=0)

In [29]:
sort_gs[-1].sum()

115.12148016521353

In [34]:
students = np.array([[1,2,3,4,5,6,7,8,9,10],
                     [135,160,163,147,138,149,136,154,137,165],
                     [34,43,40,44,41,54,39,48,35,60],
                     [4,5,4.3,5,4.7,3.9,4.2,4.9,3.7,4.6]])

In [36]:
students = students.T

In [37]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [38]:
median = np.median(students[:,-1])
median

4.449999999999999

In [39]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [43]:
median = np.median(students[:,-2])
median

42.0

In [45]:
abs(np.median(students[:,-2]) - np.mean(students[:,-2]))

1.7999999999999972

In [46]:
np.corrcoef(students[:,1], students[:,2])

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [47]:
np.corrcoef(students[:,1], students[:,3])

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [48]:
np.corrcoef(students[:,2], students[:,3])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [49]:
np.std(students[:,1])

11.083320801997928

In [50]:
np.std(students[:,-1])

0.4517742799230607

In [51]:
np.var(students[:,-2])

60.36

In [52]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [53]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [55]:
my_sin = np.sin(my_array)
my_sin.sum()

-0.05812430261413351

In [56]:
my_sin[1:4,1:4] = 1

In [57]:
my_sin.sum()

7.571718421269144

In [64]:
my_sin = my_sin[:,:4].reshape((10,2))

In [9]:
bigdata = np.array([x**2 for x in range(100,1000) if x%2])

In [11]:
np.median(bigdata)

302501.0

In [12]:
np.std(bigdata)

292095.0301991155

In [21]:
np.corrcoef(bigdata[::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])